"""add resumes + advice runs

Revision ID: 54086bfda5c7
Revises: df77906f815e
Create Date: 2026-03-03 23:23:24.169093

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '54086bfda5c7'
down_revision: Union[str, Sequence[str], None] = 'df77906f815e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rag_documents_source_id'), 'rag_documents', type_='unique')
    op.alter_column('rag_embeddings', 'embedding',
               existing_type=Vector(1536),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_embeddings', 'embedding',
               existing_type=Vector(1536),
               nullable=False)
    op.create_unique_constraint(op.f('uq_rag_documents_source_id'), 'rag_documents', ['source_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
