"""add rag documents + embeddings

Revision ID: 76408ad6ff23
Revises: deaa05f5250b
Create Date: 2026-03-03 21:37:00.192290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '76408ad6ff23'
down_revision: Union[str, Sequence[str], None] = 'deaa05f5250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_doc_type'), 'rag_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_rag_documents_source_id'), 'rag_documents', ['source_id'], unique=False)
    op.create_table('rag_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_embeddings_document_id'), 'rag_embeddings', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_embeddings_document_id'), table_name='rag_embeddings')
    op.drop_table('rag_embeddings')
    op.drop_index(op.f('ix_rag_documents_source_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_doc_type'), table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
