"""create resumes and advice_runs

Revision ID: ab0e88115b67
Revises: 54086bfda5c7
Create Date: 2026-03-03 23:51:06.940535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab0e88115b67'
down_revision: Union[str, Sequence[str], None] = '54086bfda5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_signature', sa.String(), nullable=False),
    sa.Column('resume_signature', sa.String(), nullable=False),
    sa.Column('advice_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advice_runs_profile_signature'), 'advice_runs', ['profile_signature'], unique=False)
    op.create_index(op.f('ix_advice_runs_resume_signature'), 'advice_runs', ['resume_signature'], unique=False)
    op.create_index(op.f('ix_advice_runs_user_id'), 'advice_runs', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_advice_runs_user_id'), table_name='advice_runs')
    op.drop_index(op.f('ix_advice_runs_resume_signature'), table_name='advice_runs')
    op.drop_index(op.f('ix_advice_runs_profile_signature'), table_name='advice_runs')
    op.drop_table('advice_runs')
    # ### end Alembic commands ###
