"""scorecard schools + programs

Revision ID: f866a57aa7e1
Revises: 25819cc38b62
Create Date: 2026-02-26 09:26:03.499960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f866a57aa7e1'
down_revision: Union[str, Sequence[str], None] = '25819cc38b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_unitid', sa.Integer(), nullable=False),
    sa.Column('cip2', sa.String(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_programs_cip2'), 'school_programs', ['cip2'], unique=False)
    op.create_index(op.f('ix_school_programs_school_unitid'), 'school_programs', ['school_unitid'], unique=False)
    op.drop_constraint(op.f('fk_email_verification_tokens_user_id_users'), 'email_verification_tokens', type_='foreignkey')
    op.drop_constraint(op.f('uq_profiles_user_id'), 'profiles', type_='unique')
    op.drop_constraint(op.f('fk_profiles_user_id_users'), 'profiles', type_='foreignkey')

    op.execute("DELETE FROM schools")
    
    op.add_column('schools', sa.Column('unitid', sa.Integer(), nullable=False))
    op.add_column('schools', sa.Column('city', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('zip', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('control', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('admission_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('sat_avg', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('act_mid', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('tuition_in', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('tuition_out', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('ug_enrollment', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('grad_rate_4yr', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('grad_rate_lt4', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('median_earnings_10yr', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('school_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('net_price_url', sa.String(), nullable=True))
    op.add_column('schools', sa.Column('raw_scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_schools_act_mid'), 'schools', ['act_mid'], unique=False)
    op.create_index(op.f('ix_schools_admission_rate'), 'schools', ['admission_rate'], unique=False)
    op.create_index(op.f('ix_schools_control'), 'schools', ['control'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_index(op.f('ix_schools_sat_avg'), 'schools', ['sat_avg'], unique=False)
    op.create_index(op.f('ix_schools_state'), 'schools', ['state'], unique=False)
    op.create_index(op.f('ix_schools_tuition_in'), 'schools', ['tuition_in'], unique=False)
    op.create_index(op.f('ix_schools_tuition_out'), 'schools', ['tuition_out'], unique=False)
    op.create_index(op.f('ix_schools_ug_enrollment'), 'schools', ['ug_enrollment'], unique=False)
    op.create_index(op.f('ix_schools_unitid'), 'schools', ['unitid'], unique=True)
    op.drop_column('schools', 'acceptance_rate')
    op.drop_column('schools', 'avg_gpa')
    op.drop_column('schools', 'tags')
    op.drop_column('schools', 'avg_sat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('avg_sat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('avg_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('schools', sa.Column('acceptance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_schools_unitid'), table_name='schools')
    op.drop_index(op.f('ix_schools_ug_enrollment'), table_name='schools')
    op.drop_index(op.f('ix_schools_tuition_out'), table_name='schools')
    op.drop_index(op.f('ix_schools_tuition_in'), table_name='schools')
    op.drop_index(op.f('ix_schools_state'), table_name='schools')
    op.drop_index(op.f('ix_schools_sat_avg'), table_name='schools')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_control'), table_name='schools')
    op.drop_index(op.f('ix_schools_admission_rate'), table_name='schools')
    op.drop_index(op.f('ix_schools_act_mid'), table_name='schools')
    op.drop_column('schools', 'raw_scorecard')
    op.drop_column('schools', 'net_price_url')
    op.drop_column('schools', 'school_url')
    op.drop_column('schools', 'median_earnings_10yr')
    op.drop_column('schools', 'grad_rate_lt4')
    op.drop_column('schools', 'grad_rate_4yr')
    op.drop_column('schools', 'ug_enrollment')
    op.drop_column('schools', 'tuition_out')
    op.drop_column('schools', 'tuition_in')
    op.drop_column('schools', 'act_mid')
    op.drop_column('schools', 'sat_avg')
    op.drop_column('schools', 'admission_rate')
    op.drop_column('schools', 'control')
    op.drop_column('schools', 'longitude')
    op.drop_column('schools', 'latitude')
    op.drop_column('schools', 'zip')
    op.drop_column('schools', 'city')
    op.drop_column('schools', 'unitid')
    op.create_foreign_key(op.f('fk_profiles_user_id_users'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_profiles_user_id'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_email_verification_tokens_user_id_users'), 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_school_programs_school_unitid'), table_name='school_programs')
    op.drop_index(op.f('ix_school_programs_cip2'), table_name='school_programs')
    op.drop_table('school_programs')
    # ### end Alembic commands ###
